create table if not exists public.dekanlik_records (
  id bigint generated by default as identity primary key,
  collection_key text not null,
  record_id text not null,
  payload jsonb not null,
  updated_at timestamptz not null default now(),
  unique (collection_key, record_id)
);

create or replace function public.set_dekanlik_records_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists trg_dekanlik_records_updated_at on public.dekanlik_records;

create trigger trg_dekanlik_records_updated_at
before update on public.dekanlik_records
for each row execute function public.set_dekanlik_records_updated_at();

alter table public.dekanlik_records enable row level security;

drop policy if exists "dekanlik_records_select" on public.dekanlik_records;
drop policy if exists "dekanlik_records_insert" on public.dekanlik_records;
drop policy if exists "dekanlik_records_update" on public.dekanlik_records;
drop policy if exists "dekanlik_records_delete" on public.dekanlik_records;

create policy "dekanlik_records_select"
on public.dekanlik_records for select
to anon
using (true);

create policy "dekanlik_records_insert"
on public.dekanlik_records for insert
to anon
with check (true);

create policy "dekanlik_records_update"
on public.dekanlik_records for update
to anon
using (true)
with check (true);

create policy "dekanlik_records_delete"
on public.dekanlik_records for delete
to anon
using (true);
